# Boilerplate code generated by OVITO Pro 3.6.0
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
import numpy as np

# Data import:
pipeline = import_file('red_300.lammpstrj', multiple_frames = True)

# Manual modifications of the imported data objects:
def modify_pipeline_input(frame: int, data: DataCollection):
    data.particles_.particle_types_.type_by_id_(1).name = 'Li'
    data.particles_.particle_types_.type_by_id_(2).name = 'Sc'
    data.particles_.particle_types_.type_by_id_(3).name = 'Cl'
pipeline.modifiers.append(modify_pipeline_input)

# Expression selection:
<<<<<<< HEAD
pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType == 1'))
=======
<<<<<<< HEAD
<<<<<<< HEAD
pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType == 1'))
=======
pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType == 2'))
>>>>>>> 9485a617a8c4421be2e5f2dfff0df332f6728780
>>>>>>> 4f59afea23dcf8e087f679eaf3880a81a3c04cb0
=======
pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'ParticleType == 2'))
>>>>>>> 9485a617a8c4421be2e5f2dfff0df332f6728780
>>>>>>> 74543bdbfe128396dfaf1938268f1be421c56ae4

# Invert selection:
pipeline.modifiers.append(InvertSelectionModifier())

# Coordination analysis:
pipeline.modifiers.append(CoordinationAnalysisModifier(
    cutoff = 10.0, 
<<<<<<< HEAD
    number_of_bins = 100,
    partial = True,
=======
<<<<<<< HEAD
<<<<<<< HEAD
    number_of_bins = 100,
    partial = True,
=======
    number_of_bins = 100, 
>>>>>>> 9485a617a8c4421be2e5f2dfff0df332f6728780
>>>>>>> 4f59afea23dcf8e087f679eaf3880a81a3c04cb0
=======
    number_of_bins = 100, 
>>>>>>> 9485a617a8c4421be2e5f2dfff0df332f6728780
>>>>>>> 74543bdbfe128396dfaf1938268f1be421c56ae4
    only_selected = True))

# Time averaging:
pipeline.modifiers.append(TimeAveragingModifier(
    interval = (19050, 20050), 
    operate_on = 'table:coordination-rdf'))

# Export calculated MSD value to a text file and let OVITO's data pipeline do the rest:
<<<<<<< HEAD
export_file(pipeline, 'rdf_data_sccl_partial.txt', 'txt/table', key='coordination-rdf[average]', multiple_frames=False)
=======
<<<<<<< HEAD
<<<<<<< HEAD
export_file(pipeline, 'rdf_data_sccl_partial.txt', 'txt/table', key='coordination-rdf[average]', multiple_frames=False)
=======
export_file(pipeline, 'rdf_data_licl.txt', 'txt/table', key='coordination-rdf[average]', multiple_frames=False)
>>>>>>> 9485a617a8c4421be2e5f2dfff0df332f6728780
>>>>>>> 4f59afea23dcf8e087f679eaf3880a81a3c04cb0
=======
export_file(pipeline, 'rdf_data_licl.txt', 'txt/table', key='coordination-rdf[average]', multiple_frames=False)
>>>>>>> 9485a617a8c4421be2e5f2dfff0df332f6728780
>>>>>>> 74543bdbfe128396dfaf1938268f1be421c56ae4
